const menuImages =
  // Cricket
  {
    Cricket: 'images/cricket.svg',
    Soccer: 'images/football.svg',
    Tennis: 'images/tennis.svg',
    Basketball: 'images/basketball.svg',
    Rugby: 'images/Rugbyball.png',
    Baseball: 'images/base ball.svg',
    'Horse Racing': 'images/horse.svg',
    'Greyhound Racing': 'images/greyhound-racing.png',
    Volleyball: 'images/volleyball.svg',
    Boxing: 'images/boxing.svg',
    'Ice Hockey': 'images/ice-hockey.svg',
    Snooker: 'images/Snooker.png',
    Racing: 'images/bikes.svg',
    Chess: 'images/chess.png',
    'E-games': 'images/e-games.svg',
    'Table Tennis': 'images/table-tennis-equipment.svg',
    Futsal: 'images/futsal.svg',
    Handball: 'images/handball.svg',
    Kabbadi: 'images/kabaddi.svg',
    Golf: 'images/golf.svg',
    'Rugby League': 'images/rugby.svg',
    'Rugby Union': 'images/rugby.svg',
    'Beach Volleyball': 'images/beach-volleyball.svg',
    'Mixed Martial Arts': 'images/mixed-martial-arts.svg',
    Motogp: 'images/moto-gp.svg',
    'Motor Sports': 'images/moto-gp.svg',
    Badminton: 'images/badminton.svg',
    Cycling: 'images/bicycle.svg',
    Motorbikes: 'images/motor-bikes.svg',
    Athletics: 'images/athletic.svg',
    Sumo: 'images/sumo.svg',
    'Virtual Sports': 'images/virtual-sports.svg',
    Darts: 'images/darts.svg',
    'American Football': 'images/american-football.svg',
    Esports: 'images/e games.svg',
  };

export default menuImages;
