const styles = {
    html: {
      overflowX: "hidden",
      fontFamily: "'Inter', sans-serif",
      fontSize: "15px",
      fontStyle: "normal",
      fontWeight: "600",
      lineHeight: "normal",
      backgroundColor: "black",
      color: "#FFF",
    },
    button: {
      cursor: "pointer",
    },
    colMd3ColSm12Col12FirstSidebar: {
      maxWidth: "20%",
    },
    colMd3ColSm12Col12LastSidebar: {
      maxWidth: "20%",
    },
    colMd6ColSm12Col12MiddeleContent: {
      maxWidth: "60%",
    },
    colMd6ColSm12Col12FooterArea: {
      maxWidth: "60%",
      flex: "0 0 60%",
    },
    rowFooterRowColMd3ColSm12Col12: {
      maxWidth: "20%",
    },
    navSidebar: {
      position: "fixed",
      width: "18%",
      top: "120px",
      maxHeight: "calc(100% - 130px)",
      overflowY: "scroll",
    },
    header: {
      background: "#101215",
      padding: "10px",
      marginBottom: "15px",
    },
    headerMain: {
      display: "flex",
      justifyContent: "space-between",
    },
    headerColRight: {
      display: "flex",
      width: "70%",
      justifyContent: "space-between",
      alignItems: "center",
    },
    headerColLeft: {
      width: "30%",
    },
    headerColRightHeaderRightOneUlNavMain: {
      padding: "0",
      listStyle: "none",
      margin: "0",
    },
    headerColRightHeaderRightOneUlNavMainLi: {
      display: "inline-block",
      margin: "0 10px",
    },
    headerColRightHeaderRightOneUlNavMainLiANavItems: {
      color: "#FFF",
      fontFamily: "'Inter'",
      fontSize: "15px",
      fontStyle: "normal",
      fontWeight: "600",
      lineHeight: "normal",
    },
    customButtton: {
      borderRadius: "6px",
      background: "linear-gradient(180deg, #C39E32 0%, #E7DFB3 100%)",
      padding: "10px",
      color: "#000 !important",
    },
    headerRightTwoUlButtonGroup: {
      padding: "0",
      margin: "0",
      listStyle: "none",
    },
    headerRightTwoUlButtonGroupLi: {
      display: "inline-block",
      margin: "0 5px",
    },
    footerFooter: {
      borderRadius: "15px",
      background: "#101215",
      padding: "15px",
    },
    footerTop: {
      display: "flex",
      display: "-webkit-flex",
      flexWrap: "wrap",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: "1px solid #606061",
      paddingBottom: "6px",
      marginBottom: "10px",
    },
    footerTopSecureLogo: {
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      justifyContent: "center",
      lineHeight: "normal",
    },
    ml2: {
      marginLeft: ".5rem !important",
    },
    footerTopSecureLogoImg: {
      maxHeight: "40px",
      maxWidth: "100px",
      marginRight: "0 !important",
    },
    footerTopImg: {
      maxHeight: "30px",
      maxWidth: "100px",
      marginRight: "1px",
    },
    secureLogoDiv: {
      color: "#606061",
      fontFamily: "'Inter', sans-serif",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: "700",
      lineHeight: "16px",
    },
    footerBottomSpanWsPreWrap: {
      color: "#606061",
      fontFamily: "'Inter', sans-serif",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: "700",
      lineHeight: "16px",
    },
    footerAboutUs: {
      color: "#FFF",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: "400",
      lineHeight: "18px",
      fontFamily: "'Inter', sans-serif",
    },
    footerMenuUlLiAItems: {
      color: "#FFF",
      fontFamily: "'Inter', sans-serif",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: "400",
      lineHeight: "normal",
    },
    footerMenuUlLi: {
      margin: "0",
      listStyle: "none",
    },
    footerMenuUl: {
      padding: "0",
      margin: "0",
      display: "flex",
      flexFlow: "wrap",
      gridColumnGap: "10px",
      gridRowGap: "10px",
      justifyContent: "flex-start",
    },
    footerMenu: {
      margin: "15px 0 30px 0",
    },
    footerTitleBefore: {
      content: "''",
      width: "100px",
      height: "1px",
      background: "linear-gradient(90deg, #C39E32 0%, #E7DFB3 100%)",
      position: "absolute",
      bottom: "0",
    },
    footerTitle: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: "700",
    }
}